<div class="row">
    <div class="col-md-12">
        <?php echo $this->form()->openTag($this->form) ?>
        <div class="form-group">
            <label>Department:
                <?php echo $this->formRow($this->form->get('department')) ?>
            </label>
        </div>
        <div class="form-group">
            <label>Language:
                <?php echo $this->formRow($this->form->get('language')) ?>
            </label>
        </div>
        <?php echo $this->formElement($this->form->get('submit')) ?>
        <?php echo $this->form()->closeTag() ?>
    </div>
</div>